apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk017-my-app
  labels:
    app: sk017-my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk017-my-app
  template:
    metadata:
      labels:
        app: sk017-my-app
    spec:
      containers:
        - name: sk017-my-app
          # image: amdp-registry.skala-ai.com/skala25a/sk017-my-app:1.0.0
          image: amdp-registry.skala-ai.com/skala25a/sk017-my-app@sha256:252be5e91d798b37499aa35ddf5b6abf15729073b800e7222f2d23052c48704f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
